Vitor Albuquerque de Paula

# Testar o SVM e uma MLP para o dataset IRIS: 

https://www.kaggle.com/uciml/iris
Separe aleatoriamente 70% dos dados para treino e 30% para teste e reporte com um print da saída qual a acurácia do algoritmo (número de acertos).


In [1]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

# 1. Carregar o conjunto de dados Iris
iris = datasets.load_iris()
X = iris.data
y = iris.target

# 2. Dividir os dados em conjuntos de treino e teste (70% treino, 30% teste)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# 3. Treinar um modelo SVM no conjunto de treino
svm_classifier = SVC()
svm_classifier.fit(X_train, y_train)

# 4. Avaliar o modelo no conjunto de teste e reportar a acurácia
y_pred = svm_classifier.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

accuracy


1.0

In [2]:
from sklearn.neural_network import MLPClassifier

# 2. Treinar uma MLP no conjunto de treino
mlp_classifier = MLPClassifier(random_state=42, max_iter=1000)  # max_iter aumentado para garantir convergência
mlp_classifier.fit(X_train, y_train)

# 3. Avaliar o modelo no conjunto de teste e reportar a acurácia
y_pred_mlp = mlp_classifier.predict(X_test)
accuracy_mlp = accuracy_score(y_test, y_pred_mlp)

accuracy_mlp


1.0

# Compare o resultado com os algoritmos testados na aula anterior se houve melhora na acurácia.

In [4]:
import pandas as pd

# Dados para construção do relatório
algorithms = ['KNN', 'Naive Bayes Gaussiano', 'Árvore de Decisão (Hunt)', 'SVM', 'MLP']
accuracies = [100.0, 97.78, 71.11, 100, 100]

# Construir dataframe para o relatório
report_df = pd.DataFrame({
    'Algoritmo': algorithms,
    'Acurácia (%)': accuracies
})

report_df


Algoritmo  Acurácia (%)
0                       KNN        100.00
1     Naive Bayes Gaussiano         97.78
2  Árvore de Decisão (Hunt)         71.11
3                       SVM        100.00
4                       MLP        100.00

--- 
**Análise:**

KNN, SVM e MLP alcançaram a acurácia máxima de 100%.
Naive Bayes Gaussiano teve um desempenho ligeiramente inferior, com uma acurácia de 97.78%.
Árvore de Decisão (usando o algoritmo de Hunt) teve o desempenho mais baixo entre os algoritmos testados, com uma acurácia de 71.11%.
Isso sugere que, para o conjunto de dados Iris, o KNN, SVM e MLP são os algoritmos mais adequados, enquanto a Árvore de Decisão (Hunt) pode não ser a melhor escolha.